Dogue.UI.MVC/Controllers/FiltersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Dogue.EF.DATA;
using Filter = Dogue.EF.DATA.Filter;

namespace Dogue.UI.MVC.Controllers
{
    public class FiltersController : Controller
    {
        private DogueFinalProjectEntities db = new DogueFinalProjectEntities();

        // GET: Filters
        [Authorize(Roles = "Admin, Photographer")]
        public ActionResult Index()
        {
            return View(db.Filters.ToList());
        }

        // GET: Filters/Details/5
        [Authorize(Roles = "Admin, Photographer")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Filter filter = db.Filters.Find(id);
            if (filter == null)
            {
                return HttpNotFound();
            }
            return View(filter);
        }

        // GET: Filters/Create
        [Authorize(Roles = "Admin, Photographer")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Filters/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin, Photographer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FilterID,FilterName")] Filter filter)
        {
            if (ModelState.IsValid)
            {
                db.Filters.Add(filter);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(filter);
        }

        // GET: Filters/Edit/5
        [Authorize(Roles = "Admin, Photographer")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Filter filter = db.Filters.Find(id);
            if (filter == null)
            {
                return HttpNotFound();
            }
            return View(filter);
        }

        // POST: Filters/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin, Photographer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FilterID,FilterName")] Filter filter)
        {
            if (ModelState.IsValid)
            {
                db.Entry(filter).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(filter);
        }

        // GET: Filters/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Filter filter = db.Filters.Find(id);
            if (filter == null)
            {
                return HttpNotFound();
            }
            return View(filter);
        }

        // POST: Filters/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Filter filter = db.Filters.Find(id);
            db.Filters.Remove(filter);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Dogue.UI.MVC/Views/Filters/Create.cshtml
@model Dogue.EF.DATA.Filter

@{
    ViewBag.Title = "Create";
}
<div class="container">
    <h2 class="centerMe">Create Filter</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Filter</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.FilterName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FilterName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FilterName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Dogue.UI.MVC/Views/Filters/Delete.cshtml
@model Dogue.EF.DATA.Filter

@{
    ViewBag.Title = "Delete";
}

<div class="container">
    <h2 class="centerMe">Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Filter</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.FilterName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FilterName)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</div>

Dogue.UI.MVC/Views/Filters/Details.cshtml
@model Dogue.EF.DATA.Filter

@{
    ViewBag.Title = "Details";
}
<div class="container">
    <h2 class="centerMe">Details</h2>

    <div>
        <h4>Filter</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.FilterName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FilterName)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.FilterID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>

Dogue.UI.MVC/Views/Filters/Edit.cshtml
@model Dogue.EF.DATA.Filter

@{
    ViewBag.Title = "Edit";
}
<div class="container">
    <h2 class="centerMe">Edit</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Filter</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.FilterID)

            <div class="form-group">
                @Html.LabelFor(model => model.FilterName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FilterName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FilterName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

</div>@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Dogue.UI.MVC/Views/Filters/Index.cshtml
@model IEnumerable<Dogue.EF.DATA.Filter>

@{
    ViewBag.Title = "Index";
}
<div class="container">
    <h2 class="centerMe">Photo Gallery Filters Menu</h2>
    <p class="centerMe"> Any New Or Changed Filters Must Be Updated In The HTML </P>
    @if (User.IsInRole("Admin") || User.IsInRole("Photographer"))
    {
        <p>
            @Html.ActionLink("Create New", "Create", "Filters") | @if (User.IsInRole("Admin"))
            {@Html.ActionLink("Return to Admin Menu", "AdminMenu", "Manage")}
        else
        { @Html.ActionLink("Return to Contractor Menu", "ClientMenu", "Home")}
        </p>
        <table id="datatable" class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.FilterName)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.FilterName)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.FilterID }) |
                            @Html.ActionLink("Details", "Details", new { id = item.FilterID }) |
                            @if (User.IsInRole("Admin"))
                            {
                                @Html.ActionLink("Delete", "Delete", new { id = item.FilterID })
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p> Apologies, you are not authorized to view this information.</p>
    }
</div>