Dogue.UI.MVC/Models/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Dogue.UI.MVC.Models
{
    public class ContactViewModel
    {
        [Required(ErrorMessage ="Sender name is required.")]
        public string Name { get; set; }
        [Required(ErrorMessage ="A valid email is required.")]
        [EmailAddress]
        public string Email { get; set; }
        [Required(ErrorMessage ="A subject is required.")]
        public string Subject { get; set; }
        [Required(ErrorMessage ="A message is required.")]
        [UIHint("MultilineText")]
        public string Message { get; set; }

    }
}

Dogue.UI.MVC/Controllers/HomeController.cs
using Dogue.UI.MVC.Models;
using System;
using System.Net.Mail;
using System.Web.Mvc;
using System.Net;
using System.Web;


namespace Dogue.UI.MVC.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        
        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }




        [HttpGet]
        public ActionResult Contact()
        {

            return View();
        }
        [HttpGet]
        [Authorize]
        public ActionResult ClientMenu()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Contact(ContactViewModel cvm)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Message = "Error. Please, update with the required information.";
                return View(cvm);
            }

            string body = $"{cvm.Name} has sent you the following message:<br />" +
                    $"{cvm.Message} <strong>from the email address:<strong> {cvm.Email}";
            MailMessage m = new MailMessage("no-reply@reedcoding.com", "txdmreed@outlook.com", cvm.Subject, body);
            m.IsBodyHtml = true;
            m.Priority = MailPriority.High;
            m.ReplyToList.Add(cvm.Email);
            SmtpClient client = new SmtpClient("mail.reedcoding.com");
            client.Credentials = new NetworkCredential("no-reply@reedcoding.com", "P@ssW0rd");
            client.Port = 8889;
            try
            {
                client.Send(m);
            }
            catch (Exception e)
            {
                ViewBag.Message = $"Sorry, something went wrong, please try again later or review the stacktrace<br>{e.StackTrace}";
                return View(cvm);
            }
            ViewBag.CustomerMessage = $"Message sent";
            return View("EmailConfirmation", cvm);

        }

    }
}

Dogue.UI.MVC/Controllers/PhotosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Dogue.EF.DATA;
using Dogue.UI.MVC.Models;
using Dogue.UI.MVC.Utilities;

namespace Dogue.UI.MVC.Controllers
{
    public class PhotosController : Controller
    {
        private DogueFinalProjectEntities db = new DogueFinalProjectEntities();

        // GET: Photos
        [HttpGet]
        public ActionResult Index()
        {
            
            var photos = db.Photos.Include(p => p.Filter).Include(p => p.OwnerAsset);

            return View(photos.ToList());
        }
        [HttpGet]
        public ActionResult PhotosTileView()
        {
            var photos = db.Photos.Include(p => p.Filter).Include(p => p.OwnerAsset);
            return View(photos.ToList());
        }

        [HttpGet]
        public ActionResult Portfolio()
        {
            List<PortfolioViewModel> pvm = new List<PortfolioViewModel>();
            var allPhotos = (from photo in db.Photos
                             select new { photo.PhotoID, photo.Title, photo.PhotoUrl, photo.FilterID, photo.Filter.FilterName, photo.OwnerAssetID, photo.OwnerAsset.AssetCallName, }).ToList();
            foreach (var item in allPhotos)
            {
                PortfolioViewModel objPVM = new PortfolioViewModel();

                objPVM.PhotoID = item.PhotoID;
                objPVM.FilterName = item.FilterName;
                objPVM.PhotoUrl = item.PhotoUrl;
                objPVM.Title = item.Title;
                objPVM.AssetCallName = item.AssetCallName;
                objPVM.FilterID = item.FilterID;

                pvm.Add(objPVM);
            }
            return View(pvm.ToList());
        }

        // GET: Photos/Details/5
        
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        // GET: Photos/Create
        [HttpGet]
        [Authorize(Roles = "Admin, Photographer")]
        public ActionResult Create()
        {
            ViewBag.FilterID = new SelectList(db.Filters, "FilterID", "FilterName");
            ViewBag.OwnerAssetID = new SelectList(db.OwnerAssets, "OwnerAssetID", "AssetRegisteredName");
            return View();
        }

        // POST: Photos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin, Photographer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PhotoID,Title,PhotoUrl,FilterID,OwnerAssetID")] Photo photo, HttpPostedFileBase myImg)
        {
            if (ModelState.IsValid)
            {
                #region PhotoUpload

                string imageName = "noImage.png";
                if (myImg != null)
                {
                    //Get File Extension - alternative to using a Substring () and Indexof()
                    string imgExt = System.IO.Path.GetExtension(myImg.FileName);

                    //list of allowed extentions
                    string[] allowedExtentions = { ".png", ".gif", ".jpg", ".jpeg" };
                    if (allowedExtentions.Contains(imgExt.ToLower()) && (myImg.ContentLength <= 4194304))
                    {
                        //using GUid for saved file name
                        imageName = Guid.NewGuid() + imgExt;
                        //creat some variables to pass to the resize image method
                        //Signature to resize Image
                        string savePath = Server.MapPath("~/Content/assets/img/portfolio/");

                        Image convertedImage = Image.FromStream(myImg.InputStream);
                        int maxImgSize = 1200;
                        int maxThumbSize = 100;
                        //calling this method will use the variables created above will save the full size image and thumbnail img to your server. 
                        UploadUtility.ResizeImage(savePath, imageName, convertedImage, maxImgSize, maxThumbSize);
                        ViewBag.PhotoMessage = "Photo Upload Complete.";
                    }
                    else
                    {
                        imageName = "noImage.png";
                    }
                    photo.PhotoUrl = imageName;
                }

                #endregion

                db.Photos.Add(photo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FilterID = new SelectList(db.Filters, "FilterID", "FilterName", photo.FilterID);
            ViewBag.OwnerAssetID = new SelectList(db.OwnerAssets, "OwnerAssetID", "AssetCallName", photo.OwnerAssetID);
            return View(photo);
        }

        // GET: Photos/Edit/5
        [Authorize(Roles = "Admin, Photographer")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            ViewBag.FilterID = new SelectList(db.Filters, "FilterID", "FilterName", photo.FilterID);
            ViewBag.OwnerAssetID = new SelectList(db.OwnerAssets, "OwnerAssetID", "AssetCallName", photo.OwnerAssetID);
            return View(photo);
        }

        // POST: Photos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin, Photographer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PhotoID,Title,PhotoUrl,FilterID,OwnerAssetID")] Photo photo, HttpPostedFileBase myImg)
        {
            if (ModelState.IsValid)
            {
                #region PhotoUpload
                string imageName = "noImage.png";
                if (myImg != null)
                {
                    //Get File Extension - alternative to using a Substring () and Indexof()
                    string imgExt = System.IO.Path.GetExtension(myImg.FileName);

                    //list of allowed extentions
                    string[] allowedExtentions = { ".png", ".gif", ".jpg", ".jpeg" };
                    if (allowedExtentions.Contains(imgExt.ToLower()) && (myImg.ContentLength <= 4194304))
                    {
                        //using GUid for saved file name
                        imageName = Guid.NewGuid() + imgExt;
                        //creat some variables to pass to the resize image method
                        //Signature to resize Image
                        string savePath = Server.MapPath("~/Content/assets/img/portfolio/");
                        if (photo.PhotoUrl != null && photo.PhotoUrl != "noImage.png")
                        {
                            System.IO.File.Delete(Server.MapPath("~/Content/asset/img/portfolio/S" + Session["currentImage"].ToString()));
                        }
                        photo.PhotoUrl = imageName;
                        Image convertedImage = Image.FromStream(myImg.InputStream);
                        int maxImgSize = 1200;
                        int maxThumbSize = 100;
                        //calling this method will use the variables created above will save the full size image and thumbnail img to your server. 
                        UploadUtility.ResizeImage(savePath, imageName, convertedImage, maxImgSize, maxThumbSize);

                        ViewBag.PhotoMessage = "Photo Upload Complete.";
                    }

                }

                #endregion


                db.Entry(photo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FilterID = new SelectList(db.Filters, "FilterID", "FilterName", photo.FilterID);
            ViewBag.OwnerAssetID = new SelectList(db.OwnerAssets, "OwnerAssetID", "AssetCallName", photo.OwnerAssetID);
            return View(photo);
        }

        // GET: Photos/Delete/5
        [Authorize(Roles = "Admin, Photographer")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        // POST: Photos/Delete/5
        [Authorize(Roles = "Admin, Photographer")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Photo photo = db.Photos.Find(id);
            if (photo.PhotoUrl != null && photo.PhotoUrl != "noImage.png")
            {
                System.IO.File.Delete(Server.MapPath("~/Content/asset/img/portfolio/" + Session["currentImage"].ToString()));
            }
            db.Photos.Remove(photo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Dogue.UI.MVC/Controllers/SeminarsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Dogue.EF.DATA;

namespace Dogue.UI.MVC.Controllers
{
    public class SeminarsController : Controller
    {
        private DogueFinalProjectEntities db = new DogueFinalProjectEntities();

        // GET: Seminars
        public ActionResult Index()
        {
            var seminars = db.Seminars.Include(s => s.Location);
            return View(seminars.ToList());
        }

        // GET: Seminars/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Seminar seminar = db.Seminars.Find(id);
            if (seminar == null)
            {
                return HttpNotFound();
            }
            return View(seminar);
        }

        // GET: Seminars/Create
        [Authorize(Roles = "Agent, Admin")]
        public ActionResult Create()
        {
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "LocationName");
            return View();
        }

        // POST: Seminars/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Agent, Admin")]
        public ActionResult Create([Bind(Include = "SeminarID,LocationID,SeminarReservationLimit,SeminarName,SeminarDate,SeminarNotes,SeminarSpeaker")] Seminar seminar)
        {
            if (ModelState.IsValid)
            {
                db.Seminars.Add(seminar);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "LocationName", seminar.LocationID);
            return View(seminar);
        }

        // GET: Seminars/Edit/5
        [Authorize(Roles = "Agent, Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Seminar seminar = db.Seminars.Find(id);
            if (seminar == null)
            {
                return HttpNotFound();
            }
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "LocationName", seminar.LocationID);
            return View(seminar);
        }

        // POST: Seminars/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Agent, Admin")]
        public ActionResult Edit([Bind(Include = "SeminarID,LocationID,SeminarReservationLimit,SeminarName,SeminarDate,SeminarNotes,SeminarSpeaker")] Seminar seminar)
        {
            if (ModelState.IsValid)
            {
                db.Entry(seminar).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "LocationName", seminar.LocationID);
            return View(seminar);
        }

        // GET: Seminars/Delete/5
        [Authorize(Roles = "Agent, Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Seminar seminar = db.Seminars.Find(id);
            if (seminar == null)
            {
                return HttpNotFound();
            }
            return View(seminar);
        }

        // POST: Seminars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Agent, Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Seminar seminar = db.Seminars.Find(id);
            db.Seminars.Remove(seminar);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Dogue.UI.MVC/Views/Home/ClientMenu.cshtml
@{
    ViewBag.Title = "Client Menu";
}

<div class="container">
    @if (User.IsInRole("Agent") || User.IsInRole("Photographer"))
    {
        <h2 class="centerMe">Contractor Menu</h2>
    }
    else
    {
        <h2 class="centerMe">Client Menu</h2>
    }


    <div class="gContainer">
        <div class="gContent">
            <h2 id="cardTitle">Client Information</h2>
            <p><a href="@Url.Action("Index","OwnerInformations")">Owner Information</a></p>
            <p><a href="@Url.Action("Index", "OwnerAssets")">Animal Client Information</a></p>
        </div>
    </div>
    <div class="gContainer">
        <div class="gContent">
            <h2 id="cardTitle">Portfolio</h2>
            <p><a href=" @Url.Action("Index", "Photos")">My Photos</a></p>
           
        </div>
    </div>
    <div class="gContainer">
        <div class="gContent">
            <h2 id="cardTitle">Activities Manager</h2>
            <p><a href="@Url.Action("Index","Reservations")">Animal Service Reservations</a></p>
            <p><a href="@Url.Action("Index", "Seminars")">All Seminars</a></p>
            @*<p><a href="@Url.Action("Index","MySeminars")">My Seminars</a></p>*@
        </div>
    </div>

</div>  
<hr />

Dogue.UI.MVC/Views/Home/Contact.cshtml
@model Dogue.UI.MVC.Models.ContactViewModel

<section id="contact" class="contact">
    <div class="container">

        <div class="section-title">
            <hgroup>
                <h2>Contact</h2>
            </hgroup>
            <p>I invite you to send me a note. Let me know what you think of my Dogue project.  Thank you, for checking out my work. </p>
        </div>
        <div class="row contact-info">

            <div class="col-md-4">
                <div class="contact-address">
                    <i class="icofont-google-map"></i>
                    <h3>Address</h3>
                    <address>Northland, Kansas City, MO, USA</address>
                </div>
            </div>

            <div class="col-md-4">
                <div class="contact-phone">
                    <i class="icofont-phone"></i>
                    <h3>Phone Number</h3>
                    <p>+1 719 266 2837</p>
                    <p><em>(not my phone number but fun to call)</em></p>
                </div>
            </div>

            <div class="col-md-4">
                <div class="contact-email">
                    <i class="icofont-envelope"></i>
                    <h3>Email</h3>
                    <p><a href="mailto:txdmreed@outlook.com">txdmreed@outlook.com</a></p>
                </div>
            </div>

        </div>


        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form">
                <hr />
                <div class="form-row col-md-12">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="col-md-6 form-group">

                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", placeholder = "Your Name" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })

                    </div>

                    <div class="col-md-6 form-group">

                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", placeholder = "Email" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-md-12 form-group">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control", placeholder = "Subject" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>


            <div class="form-group col-md-12">

                @Html.EditorFor(model => model.Message, new { htmlAttributes = new { @class = "form-control", placeholder= "Your Message Here"} })
                @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })

            </div>

            <div class="form-group">
                <div class="col-md-2 col-md-12 php-email-form">
                    <button type="submit">Send Message</button>
                </div>
            </div>

        }
    </div>
</section>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Dogue.UI.MVC/Views/Home/EmailConfirmation.cshtml
@model Dogue.UI.MVC.Models.ContactViewModel

@{
    ViewBag.Title = "EmailConfirmation";
}


<div class="container">
    <h2>Email Confirmation</h2>

    <div>
        <h4>Your message has been delivered.  Please allow 48hrs for a response. </h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Subject)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Subject)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Message)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Message)
            </dd>

        </dl>
    </div>
</div>

Dogue.UI.MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<!-- ======= Hero Section ======= -->
<section id="hero">
    <div class="hero-container">
        <div id="heroCarousel" class="carousel slide carousel-fade" data-ride="carousel">

            <ol class="carousel-indicators" id="hero-carousel-indicators"></ol>

            <div class="carousel-inner" role="listbox">

                <!-- Slide 1 -->
                <div class="carousel-item img-fluid active" style="background: url('/Content/assets/img/Slider/FaithWindow (1).png')top center no-repeat; background-size: cover;">
                    <div class="carousel-container">
                        <div class="carousel-content">
                            @*<h2 class="animate__animated animate__fadeInDown">Grow Your Business</h2>
                                <p class="animate__animated animate__fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid. Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut. Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore modi architecto.</p>*@
                            @*<div>
                                <a href="@Url.Action("Login","Account")" class="btn-get-started animate__animated animate__fadeInUp scrollto">Login</a>
                            </div>*@
                        </div>
                    </div>
                </div>

                <!-- Slide 2 -->
                <div class="carousel-item img-fluid" style="background: url('/Content/assets/img/Slider/BuffyPuppyPic1.png')top center no-repeat;background-size: cover;">
                    <div class="carousel-container">
                        <div class="carousel-content">
                            @*<h2 class="animate__animated animate__fadeInDown">Lorem Ipsum Dolor</h2>
                                <p class="animate__animated animate__fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid. Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut. Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore modi architecto.</p>
                                <div>
                                    <a href="@Url.Action("Login","Account")" class="btn-get-started animate__animated animate__fadeInUp scrollto">Login</a>
                                </div>*@
                        </div>
                    </div>
                </div>

                <!-- Slide 3 -->
                <div class="carousel-item img-fluid" style="background: url('/Content/assets/img/Slider/NehiBabyPic.png')top center no-repeat;background-size: cover;">
                    <div class="carousel-background">></div>
                    <div class="carousel-container">
                        <div class="carousel-content">
                            @*<img src="~/Content/assets/img/slide/slide-3.jpg" alt=""<h2 class="animate__animated animate__fadeInDown">Sequi ea ut et est quaerat</h2>
                                <p class="animate__animated animate__fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid. Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut. Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore modi architecto.</p>*@
                        </div>
                    </div>
                </div>

            </div>

            <a class="carousel-control-prev" href="#heroCarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon icofont-simple-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>

            <a class="carousel-control-next" href="#heroCarousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon icofont-simple-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>

        </div>
    </div>

</section><!-- End Hero -->